//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Employee { get; set; }
        public string Depozit { get; set; }
        public string Ransom { get; set; }
        public Nullable<int> Client { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
